# Generated by Django 2.2.7 on 2019-11-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_publist_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='publist_time',
        ),
        migrations.AddField(
            model_name='article',
            name='publish_time',
            field=models.DateTimeField(null=True),
        ),
    ]
